"use client";

import {
  User, Building2, MapPin, Briefcase, Globe, DollarSign,
  AlertCircle, CheckCircle2,
  Github, Linkedin, Twitter, ExternalLink, Phone,
} from "lucide-react";

interface LeadResearch {
  client?: {
    name?: string | null;
    contact?: string | null;
    socialLinks?: {
      linkedin?: string | null;
      github?: string | null;
      twitter?: string | null;
      personalSite?: string | null;
    };
    company?: string | null;
    location?: string | null;
    industry?: string | null;
    businessDescription?: string | null;
  };
  platforms?: {
    name?: string | null;
    projectUrl?: string | null;
    overview?: string | null;
  }[];
  budget?: {
    stated?: string | null;
    currency?: string | null;
    paymentPreference?: string | null;
  };
  generatedAt?: string | null;
}

interface Props {
  leadResearch: LeadResearch | null | undefined;
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`bg-white border border-border rounded-2xl p-6 ${className}`}>{children}</div>;
}

function SectionTitle({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <h2 className="flex items-center gap-2 text-base font-semibold text-foreground mb-4">
      {icon}{children}
    </h2>
  );
}

function Field({ label, value }: { label: string; value: string | null | undefined }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-xs font-semibold text-ternary uppercase tracking-wide">{label}</span>
      <span className={`text-sm ${value ? "text-foreground" : "text-ternary/50"}`}>{value || "N/A"}</span>
    </div>
  );
}

function TagList({ items, color = "bg-off-white text-foreground border-border" }: { items: string[]; color?: string }) {
  if (!items?.length) return <span className="text-sm text-ternary">None identified</span>;
  return (
    <div className="flex flex-wrap gap-2">
      {items.map((item, i) => (
        <span key={i} className={`px-2.5 py-1 rounded-lg text-xs font-medium border ${color}`}>
          {item}
        </span>
      ))}
    </div>
  );
}

export function LeadResearchTab({ leadResearch }: Props) {
  if (!leadResearch?.generatedAt) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-3 text-ternary">
        <AlertCircle size={32} className="opacity-30" />
        <p className="text-sm font-medium">No lead research available.</p>
        <p className="text-xs text-ternary/70">
          Lead Research is generated automatically when a lead is created with AI analysis enabled.
        </p>
      </div>
    );
  }

  const { client, platforms, budget, generatedAt } = leadResearch;

  const generatedDate = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
    : null;

  const hasSocialLinks =
    client?.socialLinks?.linkedin ||
    client?.socialLinks?.github ||
    client?.socialLinks?.twitter ||
    client?.socialLinks?.personalSite;

  return (
    <div className="space-y-5 pb-4">

      {/* Generated timestamp */}
      {generatedDate && (
        <div className="flex items-center gap-2 text-xs text-ternary">
          <CheckCircle2 size={13} className="text-success-text" />
          Research generated by Gemini AI · {generatedDate}
        </div>
      )}

      {/* Client Identity — full width */}
      <Card>
        <SectionTitle icon={<User size={18} className="text-primary" />}>Client Information</SectionTitle>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3 mb-4">
          <div className="flex items-start gap-2">
            <User size={14} className="text-ternary shrink-0 mt-0.5" />
            <Field label="Name" value={client?.name} />
          </div>
          <div className="flex items-start gap-2">
            <Phone size={14} className="text-ternary shrink-0 mt-0.5" />
            <Field label="Contact" value={client?.contact} />
          </div>
          <div className="flex items-start gap-2">
            <Building2 size={14} className="text-ternary shrink-0 mt-0.5" />
            <Field label="Company" value={client?.company} />
          </div>
          <div className="flex items-start gap-2">
            <MapPin size={14} className="text-ternary shrink-0 mt-0.5" />
            <Field label="Location" value={client?.location} />
          </div>
          <div className="flex items-start gap-2">
            <Briefcase size={14} className="text-ternary shrink-0 mt-0.5" />
            <Field label="Industry" value={client?.industry} />
          </div>
        </div>

        <div className="pb-4 mb-4 border-b border-border">
          <span className="text-xs font-semibold text-ternary uppercase tracking-wide">About</span>
          <p className={`text-sm mt-0.5 leading-relaxed ${client?.businessDescription ? "text-ternary" : "text-ternary/50"}`}>
            {client?.businessDescription || "N/A"}
          </p>
        </div>

        {/* Social Links */}
        <div>
          <p className="text-xs font-semibold text-ternary uppercase tracking-wide mb-2">Social Profiles</p>
          {hasSocialLinks ? (
            <div className="flex flex-wrap gap-2">
              {client?.socialLinks?.linkedin && (
                <a
                  href={client.socialLinks.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-blue-50 text-blue-700 border border-blue-200 hover:bg-blue-100 transition-colors"
                >
                  <Linkedin size={13} /> LinkedIn
                </a>
              )}
              {client?.socialLinks?.github && (
                <a
                  href={client.socialLinks.github}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-gray-100 text-gray-700 border border-gray-200 hover:bg-gray-200 transition-colors"
                >
                  <Github size={13} /> GitHub
                </a>
              )}
              {client?.socialLinks?.twitter && (
                <a
                  href={client.socialLinks.twitter}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-sky-50 text-sky-600 border border-sky-200 hover:bg-sky-100 transition-colors"
                >
                  <Twitter size={13} /> X / Twitter
                </a>
              )}
              {client?.socialLinks?.personalSite && (
                <a
                  href={client.socialLinks.personalSite}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-off-white text-foreground border border-border hover:bg-border transition-colors"
                >
                  <Globe size={13} /> Website
                </a>
              )}
            </div>
          ) : (
            <span className="text-sm text-ternary/50">N/A</span>
          )}
        </div>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">

        {/* Platform Discovery */}
        <Card>
          <SectionTitle icon={<Globe size={18} className="text-blue" />}>Platform Discovery</SectionTitle>
          {platforms && platforms.length > 0 ? (
            <div className="space-y-5">
              {platforms.map((p, i) => (
                <div key={i} className={i > 0 ? "pt-4 border-t border-border" : ""}>
                  <div className="space-y-3">
                    <Field label="Platform" value={p.name} />
                    <div className="flex flex-col gap-1">
                      <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Project Posting URL</span>
                      {p.projectUrl ? (
                        <a
                          href={p.projectUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-start gap-1.5 text-sm text-primary hover:underline break-all"
                        >
                          <ExternalLink size={13} className="shrink-0 mt-0.5" />
                          {p.projectUrl}
                        </a>
                      ) : (
                        <span className="text-sm text-ternary/50">N/A</span>
                      )}
                    </div>
                    <div className="flex flex-col gap-1">
                      <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Platform Overview</span>
                      <p className={`text-sm leading-relaxed ${p.overview ? "text-ternary" : "text-ternary/50"}`}>{p.overview || "N/A"}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-sm text-ternary/50">N/A — no public posting found</p>
          )}
        </Card>

        {/* Budget */}
        <Card>
          <SectionTitle icon={<DollarSign size={18} className="text-success-text" />}>Client Budget</SectionTitle>
          <div className="space-y-3">
            <div className="flex flex-col gap-1">
              <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Stated Budget</span>
              {budget?.stated ? (
                <span className="text-lg font-bold text-foreground">{budget.stated}</span>
              ) : (
                <span className="text-sm text-ternary/50">N/A</span>
              )}
            </div>
            <div className="grid grid-cols-2 gap-3 pt-2 border-t border-border">
              <Field label="Currency" value={budget?.currency} />
              <Field label="Payment Type" value={budget?.paymentPreference} />
            </div>
          </div>
        </Card>
      </div>

    </div>
  );
}
