"use client";

import {
  User, Building2, MapPin, Briefcase, Globe, Lightbulb,
  DollarSign, Clock, TrendingUp, Layers, Cpu, Plug,
  Monitor, AlertCircle, CheckCircle2,
} from "lucide-react";

interface LeadResearch {
  client?: {
    name?: string | null;
    company?: string | null;
    location?: string | null;
    industry?: string | null;
    companySize?: string | null;
    businessDescription?: string | null;
  };
  platform?: {
    source?: string | null;
    postingContext?: string | null;
    urgencyLevel?: string | null;
    typicalBudgetRange?: string | null;
  };
  projectStatus?: {
    phase?: string | null;
    decisionTimeline?: string | null;
    competitiveLandscape?: string | null;
  };
  budget?: {
    stated?: string | null;
    estimatedRange?: string | null;
    currency?: string | null;
    paymentPreference?: string | null;
  };
  coreRequirements?: {
    summary?: string | null;
    features?: string[];
    technicalConstraints?: string[];
    integrations?: string[];
    platforms?: string[];
  };
  researchInsights?: string[];
  generatedAt?: string | null;
}

interface Props {
  leadResearch: LeadResearch | null | undefined;
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <div className={`bg-white border border-border rounded-2xl p-6 ${className}`}>{children}</div>;
}

function SectionTitle({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <h2 className="flex items-center gap-2 text-base font-semibold text-foreground mb-4">
      {icon}{children}
    </h2>
  );
}

function Field({ label, value }: { label: string; value: string | null | undefined }) {
  if (!value) return null;
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-xs font-semibold text-ternary uppercase tracking-wide">{label}</span>
      <span className="text-sm text-foreground">{value}</span>
    </div>
  );
}

function TagList({ items, color = "bg-off-white text-foreground border-border" }: { items: string[]; color?: string }) {
  if (!items?.length) return <span className="text-sm text-ternary">None identified</span>;
  return (
    <div className="flex flex-wrap gap-2">
      {items.map((item, i) => (
        <span key={i} className={`px-2.5 py-1 rounded-lg text-xs font-medium border ${color}`}>
          {item}
        </span>
      ))}
    </div>
  );
}

function urgencyColor(level: string | null | undefined) {
  if (!level) return "bg-off-white text-ternary border-border";
  if (level.toLowerCase() === "high") return "bg-error-bg text-error-text border-red-200";
  if (level.toLowerCase() === "medium") return "bg-yellow-50 text-yellow-700 border-yellow-200";
  return "bg-success-bg text-success-text border-green-200";
}

export function LeadResearchTab({ leadResearch }: Props) {
  if (!leadResearch?.generatedAt) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-3 text-ternary">
        <AlertCircle size={32} className="opacity-30" />
        <p className="text-sm font-medium">No lead research available.</p>
        <p className="text-xs text-ternary/70">
          Lead Research is generated automatically when a lead is created with AI analysis enabled.
        </p>
      </div>
    );
  }

  const { client, platform, projectStatus, budget, coreRequirements, researchInsights, generatedAt } = leadResearch;

  const generatedDate = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
    : null;

  return (
    <div className="space-y-5 pb-4">

      {/* Generated timestamp */}
      {generatedDate && (
        <div className="flex items-center gap-2 text-xs text-ternary">
          <CheckCircle2 size={13} className="text-success-text" />
          Research generated by Gemini AI · {generatedDate}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">

        {/* Client Profile */}
        <Card>
          <SectionTitle icon={<Building2 size={18} className="text-primary" />}>Client Profile</SectionTitle>
          <div className="space-y-3">
            {client?.name && (
              <div className="flex items-center gap-2">
                <User size={14} className="text-ternary shrink-0" />
                <span className="text-sm text-foreground font-medium">{client.name}</span>
              </div>
            )}
            {client?.company && (
              <div className="flex items-center gap-2">
                <Building2 size={14} className="text-ternary shrink-0" />
                <span className="text-sm text-foreground">{client.company}</span>
              </div>
            )}
            {client?.location && (
              <div className="flex items-center gap-2">
                <MapPin size={14} className="text-ternary shrink-0" />
                <span className="text-sm text-foreground">{client.location}</span>
              </div>
            )}
            {client?.industry && (
              <div className="flex items-center gap-2">
                <Briefcase size={14} className="text-ternary shrink-0" />
                <span className="text-sm text-foreground">{client.industry}</span>
              </div>
            )}
            {client?.companySize && (
              <div className="flex items-center gap-2">
                <Globe size={14} className="text-ternary shrink-0" />
                <span className="text-sm text-foreground">{client.companySize}</span>
              </div>
            )}
            {client?.businessDescription && (
              <p className="text-sm text-ternary leading-relaxed pt-1 border-t border-border mt-3">
                {client.businessDescription}
              </p>
            )}
            {!client?.name && !client?.company && !client?.businessDescription && (
              <p className="text-sm text-ternary">No client information could be identified.</p>
            )}
          </div>
        </Card>

        {/* Platform & Context */}
        <Card>
          <SectionTitle icon={<Globe size={18} className="text-blue" />}>Platform & Context</SectionTitle>
          <div className="space-y-4">
            {platform?.source && (
              <Field label="Source Platform" value={platform.source} />
            )}
            {platform?.urgencyLevel && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Urgency</span>
                <span className={`self-start px-2.5 py-1 rounded-lg text-xs font-semibold border ${urgencyColor(platform.urgencyLevel)}`}>
                  {platform.urgencyLevel}
                </span>
              </div>
            )}
            {platform?.typicalBudgetRange && (
              <Field label="Typical Budget on This Platform" value={platform.typicalBudgetRange} />
            )}
            {platform?.postingContext && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Posting Context</span>
                <p className="text-sm text-ternary leading-relaxed">{platform.postingContext}</p>
              </div>
            )}
          </div>
        </Card>

        {/* Project Status */}
        <Card>
          <SectionTitle icon={<TrendingUp size={18} className="text-purple" />}>Project Status</SectionTitle>
          <div className="space-y-3">
            {projectStatus?.phase && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Buying Phase</span>
                <span className="self-start px-2.5 py-1 rounded-lg text-xs font-semibold bg-primary/10 text-primary border border-primary/20">
                  {projectStatus.phase}
                </span>
              </div>
            )}
            {projectStatus?.decisionTimeline && (
              <div className="flex items-start gap-2">
                <Clock size={14} className="text-ternary shrink-0 mt-0.5" />
                <div>
                  <p className="text-xs font-semibold text-ternary uppercase tracking-wide mb-0.5">Decision Timeline</p>
                  <p className="text-sm text-foreground">{projectStatus.decisionTimeline}</p>
                </div>
              </div>
            )}
            {projectStatus?.competitiveLandscape && (
              <div className="flex flex-col gap-1 pt-2 border-t border-border">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Competitive Landscape</span>
                <p className="text-sm text-ternary leading-relaxed">{projectStatus.competitiveLandscape}</p>
              </div>
            )}
          </div>
        </Card>

        {/* Budget Intelligence */}
        <Card>
          <SectionTitle icon={<DollarSign size={18} className="text-success-text" />}>Budget Intelligence</SectionTitle>
          <div className="space-y-3">
            {budget?.stated && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Client Stated Budget</span>
                <span className="text-lg font-bold text-foreground">{budget.stated}</span>
              </div>
            )}
            {budget?.estimatedRange && (
              <div className="flex flex-col gap-1">
                <span className="text-xs font-semibold text-ternary uppercase tracking-wide">Realistic Estimate</span>
                <span className="text-sm text-ternary leading-relaxed">{budget.estimatedRange}</span>
              </div>
            )}
            <div className="grid grid-cols-2 gap-3 pt-2 border-t border-border">
              <Field label="Currency" value={budget?.currency} />
              <Field label="Payment Type" value={budget?.paymentPreference} />
            </div>
          </div>
        </Card>
      </div>

      {/* Core Requirements */}
      <Card>
        <SectionTitle icon={<Layers size={18} className="text-primary" />}>Core Project Requirements</SectionTitle>
        {coreRequirements?.summary && (
          <p className="text-sm text-ternary leading-relaxed mb-5">{coreRequirements.summary}</p>
        )}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {(coreRequirements?.features?.length ?? 0) > 0 && (
            <div>
              <p className="flex items-center gap-1.5 text-sm font-semibold text-foreground mb-2">
                <CheckCircle2 size={14} className="text-success-text" />Key Features
              </p>
              <TagList items={coreRequirements!.features!} color="bg-success-bg text-success-text border-green-200" />
            </div>
          )}
          {(coreRequirements?.platforms?.length ?? 0) > 0 && (
            <div>
              <p className="flex items-center gap-1.5 text-sm font-semibold text-foreground mb-2">
                <Monitor size={14} className="text-blue" />Target Platforms
              </p>
              <TagList items={coreRequirements!.platforms!} color="bg-blue-50 text-blue border-blue-200" />
            </div>
          )}
          {(coreRequirements?.integrations?.length ?? 0) > 0 && (
            <div>
              <p className="flex items-center gap-1.5 text-sm font-semibold text-foreground mb-2">
                <Plug size={14} className="text-primary" />Integrations Needed
              </p>
              <TagList items={coreRequirements!.integrations!} color="bg-primary/10 text-primary border-primary/20" />
            </div>
          )}
          {(coreRequirements?.technicalConstraints?.length ?? 0) > 0 && (
            <div>
              <p className="flex items-center gap-1.5 text-sm font-semibold text-foreground mb-2">
                <Cpu size={14} className="text-ternary" />Technical Constraints
              </p>
              <TagList items={coreRequirements!.technicalConstraints!} color="bg-yellow-50 text-yellow-700 border-yellow-200" />
            </div>
          )}
        </div>
      </Card>

      {/* Research Insights */}
      {(researchInsights?.length ?? 0) > 0 && (
        <Card>
          <SectionTitle icon={<Lightbulb size={18} className="text-yellow" />}>Research Insights</SectionTitle>
          <ol className="space-y-3">
            {researchInsights!.map((insight, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="shrink-0 w-6 h-6 rounded-full bg-yellow-50 border border-yellow-200 text-xs font-bold text-yellow-700 flex items-center justify-center mt-0.5">
                  {i + 1}
                </span>
                <p className="text-sm text-ternary leading-relaxed">{insight}</p>
              </li>
            ))}
          </ol>
        </Card>
      )}

    </div>
  );
}
